### ISSUE TITLE
Sometimes the run is paused

### ISSUE THREAD

**Issue by halverd2** [awadhn/robotframework-run-keyword-async#1]
I've used the keyword "Run Keyword Async" and sometimes the execution of the test is stopped and never continued. This is always seen when the function executed with the "Run Keyword Async" keyword is being execued.

**Comment by awadhn** [comment]
Did you try latest build? We have moved to use process instead of thread? 
There is also a timer running to come out if something goes bad. Please share your robot file if possible to look.

**Comment by awadhn** [comment]
With multiprocessing, we have not seen this issue. Please let me know if you are still facing any issue.
