### ISSUE TITLE
PicklingError: Can't pickle <function wrapped_f at 0x03F47030>: it's not found as runKeywordAsync.runKeywordAsync.wrapped_f

### ISSUE THREAD

**Issue by akki-12345** [awadhn/robotframework-run-keyword-async#3]
I am trying to run multiple keywords under single test Scripts.But I am getting above error.Please give any solution for that

**Comment by kirthi2468** [comment]
Same here. I'm getting the error . I'm using python 2.7

**Comment by jcuyag** [comment]
I concur on the same problem while running on python 3.5

**Comment by rkumarrb** [comment]
Same here any idea why its happening?

**Comment by JonathanStrandberg** [comment]
Same here on python 2.7. Any success with it?

**Comment by geoff-coppertop** [comment]
I'm seeing the same thing with python 3.6.5

**Comment by awadhn** [comment]
Hi,

It is written for Python3 and below sample robot works for me. 

*** Settings ***
Library   runKeywordAsync 

*** Variables ***
*** Test Cases ***
TC1
    Run Keyword Async   KEY1   show chassis hardware
    Run Keyword Async   KEY2   show chassis hardware

    Log To Console   \n"Hello back in main process and waiting for threads"
    ${out}=   Wait Async All   timeout=60

    Log To Console   \n"Done with execution with output" 
    Log To Console   \n${out} 

*** Keywords ***
KEY1
    [Arguments]   ${command}
    ${tmp}=   Get Variable Value  ${command}
    Log To Console   ${command}
    [RETURN]   1 
KEY2
    [Arguments]   ${command}
    Log To Console   ${command}
    [RETURN]   1
