### ISSUE TITLE
No keyword with name 'Run Keyword Async' Found 

### ISSUE THREAD

**Issue by MiGrue** [awadhn/robotframework-run-keyword-async#4]
I tried to use this library to execute som long running checks in parallel but i cant get it working. Always get the error that the keywords are not found.
Other Librarys are working fine.

Any Idea?

**Comment by awadhn** [comment]
Below works for me. 

*** Settings ***
Library   runKeywordAsync 

*** Variables ***
*** Test Cases ***
TC1
    Run Keyword Async   KEY1   show chassis hardware
    Run Keyword Async   KEY2   show chassis hardware

    Log To Console   \n"Hello back in main process and waiting for threads"
    ${out}=   Wait Async All   timeout=60

    Log To Console   \n"Done with execution with output" 
    Log To Console   \n${out} 

*** Keywords ***
KEY1
    [Arguments]   ${command}
    ${tmp}=   Get Variable Value  ${command}
    Log To Console   ${command}
    [RETURN]   1 
KEY2
    [Arguments]   ${command}
    Log To Console   ${command}
    [RETURN]   1

**Comment by sankonam** [comment]
i tried this keyword i also get same error No keyword with name 'Run Keyword Async' found
